services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=sudogest
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_ROOT_PASSWORD=pass123
    networks:
      - sameNetworkAsMysql
    ports:
      - 3307:3306
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

  api1:
    build:
      context: ./backend_api1
      dockerfile: Dockerfile
    networks:
      - sameNetworkAsMysql
    depends_on:
      - db

  api2:
    build:
      context: ./backend_api2
      dockerfile: Dockerfile
    networks:
      - sameNetworkAsMysql
    depends_on:
      - db


  frontend:
    restart: on-failure
    build:
      context: ./frontend
    ports:
      - 3001:3000
    networks:
      - sameNetworkAsMysql
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: sudogest_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - sameNetworkAsMysql


networks:
  sameNetworkAsMysql:
    driver: bridge
